name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.13", "2.13.5"]
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - name: Test JVM
        run: sbt "++${{ matrix.scalaversion }}" testSuiteJVM/test
      - name: Test JS
        run: sbt "++${{ matrix.scalaversion }}" testSuiteJS/test
      - name: Doc generation
        run: sbt "++${{ matrix.scalaversion }}" root/doc
      - name: Header check
        run: sbt "++${{ matrix.scalaversion }}" root/headerCheck testSuiteJVM/test:headerCheck testSuiteJS/test:headerCheck
